### ISSUE TITLE
bug: The icon for the indented code block is missing

### ISSUE THREAD

**Issue by MasouShizuka** [MeanderingProgrammer/markdown.nvim#60] opened 2024-07-11 02:19 UTC
### Neovim version (nvim -v)

0.10.0

### Operating system

Windows11

### Terminal emulator / GUI

WezTerm

### Describe the bug

Unindented code blocks behave normally, but the icon for indented code blocks is missing, like:
![image](https://github.com/MeanderingProgrammer/markdown.nvim/assets/44764707/43ca0b35-2269-4519-b949-240a343101df)

source code is:
![image](https://github.com/MeanderingProgrammer/markdown.nvim/assets/44764707/c3b86d39-0258-49a7-8e2c-966a560e021d)

### Expected behavior

The icon for indented code blocks should exist.

### Healthcheck output (:checkhealth render-markdown)

```
render-markdown: require("render-markdown.health").check()

markdown.nvim [nvim-treesitter] ~
- OK installed
- OK markdown: parser installed
- OK markdown_inline: parser installed
- OK highlights enabled

markdown.nvim [executables] ~
- OK none to check

markdown.nvim [configuration] ~
- OK valid
```

**Comment by MeanderingProgrammer** [comment] 2024-07-11 04:02
Can you provide the raw markdown for your example?

I am seeing the same when you put a slightly indented code block under another code block, but it actually works if I put it under a list. Am wondering if it has to do with how far indented things are.

There's also a separate issue of [indented_code_block](https://www.jetbrains.com/help/hub/markdown-syntax.html#indented-code-blocks), which this plugin does not support.

**Comment by MasouShizuka** [comment] 2024-07-11 06:57
I found something strange. If the indent is 2, the icon will not be missing:
![image](https://github.com/MeanderingProgrammer/markdown.nvim/assets/44764707/8a0c0476-648b-49e5-a7b6-cb5c9b99567d)

source code is:
![image](https://github.com/MeanderingProgrammer/markdown.nvim/assets/44764707/fba81fc7-b77c-4c52-98dc-2c7162ffb21f)

**Comment by MeanderingProgrammer** [comment] 2024-07-11 07:00
Yeah, I found the same thing.

I think I figured out the cause, not even sure why I even tried this, but it seems to be an interaction with [indent-blankline.nvim](https://github.com/lukas-reineke/indent-blankline.nvim).

If I disable indent blank line then everything starts working as expected, no random cutoff of language.

I'll try to see what's going on there.

**Comment by MasouShizuka** [comment] 2024-07-11 07:18
You are right, after I disabled `indent-blankline.nvim`, I can also see the icon when indent is 4.

**Comment by MeanderingProgrammer** [comment] 2024-07-11 10:57
Ah it was a combination of indent blank lines overlaying the leading spaces as well as the code fence capturing the leading space. So when things got concealed they were left shifted then overlayed.

Handling it is pretty straightforward pushed a fix here: https://github.com/MeanderingProgrammer/markdown.nvim/commit/48083f81aa1100293b92755a081764f61dce2f1f.

LMK if it works for you as well!

**Comment by MasouShizuka** [comment] 2024-07-11 11:04
After taking a quick look at some of my notes, this should be able to display the icon normally.

**Comment by MeanderingProgrammer** [comment] 2024-07-11 19:32
Sweet, closing the issue, feel free to re-open if you come across something.

**Closed by MeanderingProgrammer** 2024-07-11 19:32 UTC
Labels: bug
