### ISSUE TITLE
Highlight only in the markdown injection area for non-markdown file?

### ISSUE THREAD

**Issue by lkhphuc** [MeanderingProgrammer/markdown.nvim#3] opened 2024-03-22 07:49 UTC
Hi, I'm the one asking about activating this plugin on other file type on reddit. Thanks for quickly adding the ability.
My use case currently is I inject markdown highlight on all the code standalone multi-line string in python.
With this the standard markdown highlighting work perfectly.
```
; after/queries/python/injections.scm
;extends

(module
  (expression_statement
    (string
      (string_content) @injection.content)
    )
  (#set! injection.language "markdown")
  )

```
With this plugin enabled for python file, the highlighting does work, but I noticed it also highlight the python comments, outside of the """ multiline string that is injected as markdown.

<img width="862" alt="Screenshot 2024-03-22 at 14 48 43" src="https://github.com/MeanderingProgrammer/markdown.nvim/assets/12573521/01a38ac4-3b67-44b8-8b22-5d0a3a91f283">

Do you know a way to restrict the highlighting just to this injected markdown reason?

**Comment by MeanderingProgrammer** [comment] 2024-03-23 00:11
This should be resolved with the following change: https://github.com/MeanderingProgrammer/markdown.nvim/commit/e64255d52dcdf05eb37d9e93fbfd300648c4c4dd.

Please update the plugin and let me know if it behaves as intended.

**Closed** 2024-03-23 00:12 UTC
Labels: enhancement
